# Generated by Django 5.1.6 on 2025-02-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PDFMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="Size in bytes"),
                ),
                ("num_pages", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("text_extracted", models.BooleanField(default=False)),
                ("images_extracted", models.PositiveIntegerField(default=0)),
                ("merged_pdf", models.BooleanField(default=False)),
            ],
        ),
    ]
