name: Deploy to AWS EC2

on:
  push:
    branches:
      - master  # Change if your main branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/pdf-wizard-backend  # Navigate to the project directory

          # Pull the latest code
          git pull origin master

          # Activate the virtual environment inside the project directory
          source env/bin/activate

          # Install dependencies
          pip install -r requirements.txt

          # Run database migrations
          python manage.py migrate

          # Collect static files
          python manage.py collectstatic --noinput

          # Restart Gunicorn and Nginx
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
          EOF


