name: Deploy to AWS EC2

on:
  push:
    branches:
      - master  # Change if your main branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/pdf-wizard-backend  # Change to your project path
          git pull origin main  # Pull latest code
          source /home/ubuntu/.venv/bin/activate  # Activate virtual environment
          pip install -r requirements.txt  # Install dependencies
          python manage.py migrate  # Run migrations
          python manage.py collectstatic --noinput  # Collect static files
          sudo systemctl restart gunicorn  # Restart Gunicorn
          sudo systemctl restart nginx  # Restart Nginx
          EOF

